# golangci-lint v2 configuration
# Run: golangci-lint run
version: "2"

run:
  modules-download-mode: readonly

linters:
  enable:
    - errname       # Error naming conventions
    - errorlint     # Error wrapping issues
    - gocritic      # Opinionated linter
    - gosec         # Security issues
    - misspell      # Catch typos
    - revive        # Fast, configurable linter
    - unconvert     # Remove unnecessary conversions

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false  # Allow _ = to explicitly ignore errors

    gocritic:
      enabled-tags:
        - diagnostic
        - performance

    gosec:
      excludes:
        - G204  # Subprocess with variable args (expected for guard command)
        - G302  # File permissions (0644 is fine for lock files)
        - G304  # File path from variable (expected for file operations)

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Micro-optimization, not worth the churn
        - shadow          # Too noisy in tests

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        # Disabled: exported, package-comments (too noisy for small CLIs)

  exclusions:
    generated: lax
    rules:
      # Allow type assertions on errors in main (CLI simplicity)
      - linters:
          - errorlint
        path: cmd/lokt/main.go
        text: type assertion on error
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt       # Check formatting
    - goimports   # Check imports

  settings:
    goimports:
      local-prefixes:
        - github.com/nikolasavic/lokt

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
